markdown: rdiscount
permalink: /:title/
url: http://leeran.me
name: 秋水时至 百川灌河
author: 李然
qq: 
email: leeran@foxmail.com
duoshuo: 
beian: 
cnzz: 
weibo: 
github: lithur
pygments: true
safe: true
paginate: 20
about: "这是关于此博客的介绍，目前表示没有太多想说的。"
